### PR TITLE
add ability to register aggr defs

### PR DESCRIPTION
**Pull request by AlexBedley**
Boom! No more DB hackery.

@csilcock
@tfletcher

### CODE REVIEW

**Comment by csilcock** [comment]
Can we register all unknown/unsupported aggregations with an ID of 0 as well? The reason I ask this, is so that the reconciler doesn't keep running every 15 minutes and chew up our request limit.

**Comment by csilcock** [comment]
other than that :shipit:

**Comment by AlexBedley** [comment]
> Can we register all unknown/unsupported aggregations with an ID of 0 as well? The reason I ask this, is so that the reconciler doesn't keep running every 15 minutes and chew up our request limit.

It does that implicitly (the metron client in the lms does that automatically if there are no errors)

**Comment by AlexBedley** [comment]
Found some errors in the datagen, gonna hold off until I fix them.

**Comment by tinafletcher** [comment]
Looks good to me, definitely a cool enhancement that will make things easier!

**Comment by csilcock** [comment]
:shipit:

**Comment by AlexBedley** [comment]
You guys cool with me merging this now? It turns out the bug earlier was just me not using the thing properly

**Comment by csilcock** [comment]
:shipit:

**Comment by tinafletcher** [comment]
:shipit:

**Comment by AlexBedley** [comment]
oh I don't have write access so someone else will have to merge this. Or add me as a collaborator.

**Pull request merged**
